name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy to Server
        run: |
          cd ~/Menus_Electron
          eval "$(ssh-agent -s)"
          ssh-add ~/gith
          git stash
          sudo -E git pull
          yarn install
          yarn build
          yarn dist:win
